### ISSUE TITLE
NODE_ENV: '"production"'，其实是不需要webstorm-disable-index的

### ISSUE THREAD

**Issue by taotao365s** [coolme200/webstorm-disable-index#6]
在构建时不需要检测.idea目录的，否则会报错
![qq 20170327152424](https://cloud.githubusercontent.com/assets/1212932/24345199/887fda0c-1301-11e7-9a1d-b937055237be.png)

**Comment by atian25** [comment]
你指的是线上？ 这个插件应该是 devdeps，只在本地用的

**Comment by taotao365s** [comment]
@atian25 我明白你的意思了，
